SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  docker
  aws
  terraform
  line_sep
  exit_code
  char
)

SPACESHIP_RPROMPT_ORDER=(
  venv
  conda
  python
)

# Prompt
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_DEFAULT_PREFIX=" "
SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true

# Prompt char
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SECONDARY_SYMBOL=" ❯ "
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS=green

# Username
SPACESHIP_USER_SHOW=true
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX=""
SPACESHIP_USER_COLOR=green

# Hostname
SPACESHIP_HOST_SHOW=needed
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_COLOR=yellow
SPACESHIP_HOST_COLOR_SSH=cyan

# Directory
SPACESHIP_DIR_PREFIX=" ["
SPACESHIP_DIR_SUFFIX="] "
SPACESHIP_DIR_TRUNC_PREFIX="…/"
SPACESHIP_DIR_COLOR=blue

# Git
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SYMBOL=" "
SPACESHIP_GIT_STATUS_DELETED="-"

# Python venv
SPACESHIP_VENV_SYMBOL=" "
SPACESHIP_VENV_COLOR=yellow
SPACESHIP_VENV_VERBOSE=false

# Conda env
SPACESHIP_CONDA_SYMBOL="🅒 "
SPACESHIP_CONDA_COLOR=yellow
SPACESHIP_CONDA_VERBOSE=false

# Python version
SPACESHIP_PYTHON_SHOW=true
SPACESHIP_PYTHON_PREFIX=""
SPACESHIP_PYTHON_SYMBOL="| "
SPACESHIP_PYTHON_COLOR=yellow
